name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    env:
      DATE_TAG: dev-${{ github.run_id }}-$(date +%Y%m%d%H%M)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend Docker Image
        working-directory: ./backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:${DATE_TAG} -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:${DATE_TAG}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Discord Notification
        uses: Ilshidur/action-discord@master
        with:
          args: "✅ [BACKEND] 이미지 푸시 완료: `${{ env.DATE_TAG }}`"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
