name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    env:
      DATE_TAG: dev-${{ github.run_id }}-${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ env.DATE_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
    
      - name: Deploy via Bastion Host
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          port: 2022
          key: ${{ secrets.EC2_SSH_KEY }}        
          proxy_host: ${{ secrets.BASTION_HOST }} 
          proxy_username: ${{ secrets.EC2_USERNAME }}
          proxy_key: ${{ secrets.EC2_SSH_KEY }} 
          script: |
            cd ~/test
            ./deploy.sh backend

      - name: Discord Notification
        if: success()
        uses: Ilshidur/action-discord@master
        with:
          args: "✅ [BACKEND] 이미지 푸시 완료: `${{ env.DATE_TAG }}`"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
