name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    env:
      DATE_TAG: dev-${{ github.run_id }}-${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Frontend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ env.DATE_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      - name: Discord Notification
        if: success()
        uses: Ilshidur/action-discord@master
        with:
          args: "✅ [FRONTEND] 이미지 푸시 완료: `${{ env.DATE_TAG }}`"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Deploy via Bastion Host
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEV_HOST }}         
          username: ${{ secrets.EC2_USERNAME }}
          port: 2022
          key: ${{ secrets.EC2_SSH_KEY }}        
          proxy_host: ${{ secrets.BASTION_HOST }}
          proxy_username: ${{ secrets.EC2_USERNAME }}
          proxy_key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/test
            ./deploy.sh frontend
